name: main

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
      - '**.yaml'
      - '**.yml'
      - '**.launch'
  pull_request:
    branches: [ master ]

  schedule:
    - cron:  '0 0 * * *' # at the end of every day

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  cancel:

    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ros2_distro: [galactic]

    steps:

      - name: Download ROS2-Galactic
        uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: galactic

      - name: Checkout fog_lib
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch the whole history

      - name: Build
        run: ./.ci/build.sh

      - name: Test
        run: ./.ci/test.sh
